/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jogo.telas;

import javax.swing.JOptionPane;
import java.sql.*;
import br.com.jogo.dal.ModeloConexao;

/**
 *
 * @author Julimar
 */
public class TelaCadastroJogador extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicial
     */
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;

    public static int idJogadorAtual = 0;

    public TelaCadastroJogador() {
        initComponents();
        conexao = ModeloConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtCadJogador = new javax.swing.JTextField();
        btnPaginaInicial = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Duelo de Equação - Regras");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nome do jogador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtCadJogador.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jPanel1.add(txtCadJogador, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 470, 60));

        btnPaginaInicial.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/home.png"))); // NOI18N
        btnPaginaInicial.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaginaInicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaginaInicialActionPerformed(evt);
            }
        });
        jPanel1.add(btnPaginaInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 120, -1));

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/next.png"))); // NOI18N
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });
        jPanel1.add(btnProximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 200, 110, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 510, 310));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/img/background.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, -10, 670, 750));

        setSize(new java.awt.Dimension(544, 767));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void nomeJogador() {
        String nome = txtCadJogador.getText().trim();
        if (nome.isEmpty()) {
            JOptionPane.showMessageDialog(null, "INFORME O NOME DO JOGADOR", "ERRO NO CADASTRO", JOptionPane.WARNING_MESSAGE);
            txtCadJogador.requestFocus();
        } else {
            String sql = "insert into tbjogador (nomejogador) values (?)";
            try (Connection conexaoAtual = ModeloConexao.conector();
                    java.sql.PreparedStatement pst = conexaoAtual.prepareStatement(
                            sql,
                            java.sql.Statement.RETURN_GENERATED_KEYS
                    )) {

                pst.setString(1, txtCadJogador.getText().trim().toUpperCase());
                int adicionar = pst.executeUpdate();

                if (adicionar > 0) {
                    try (java.sql.ResultSet rs = pst.getGeneratedKeys()) {
                        if (rs.next()) {
                            idJogadorAtual = rs.getInt(1);
                            System.out.println("ID do Jogador Capturado: " + idJogadorAtual);
                        }
                    }

                    JOptionPane.showMessageDialog(null, "JOGADOR CADASTRADO COM SUCESSO!");
                    TelaPerguntas perguntas = new TelaPerguntas();
                    perguntas.setVisible(true);
                    this.setVisible(false);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "ERRO NO CADASTRO/CONEXÃO: " + e.getMessage(), "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void btnPaginaInicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaginaInicialActionPerformed
        // Chamando a tela inicial 
        TelaInicial inicio = new TelaInicial();
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnPaginaInicialActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        // Chamando a tela Perguntas
        nomeJogador();
    }//GEN-LAST:event_btnProximoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastroJogador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastroJogador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaginaInicial;
    private javax.swing.JButton btnProximo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCadJogador;
    // End of variables declaration//GEN-END:variables
}
